// <auto-generated />
using System;
using Infra.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Repository.Migrations
{
    [DbContext(typeof(FinanceiroContext))]
    partial class FinanceiroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasColumnType("varchar(40)")
                        .HasColumnName("codigo_banco");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_banco");

                    b.Property<decimal>("PercentualJuros")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("percentual_juros");

                    b.HasKey("Id");

                    b.ToTable("tb_banco", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BancoId")
                        .HasColumnType("integer")
                        .HasColumnName("banco_id");

                    b.Property<string>("CpfCnpfBeneficiario")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpfcnpj_beneficiario");

                    b.Property<string>("CpfCnpjPagador")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpfcnpj_pagador");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeBeneficiario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_beneficiario");

                    b.Property<string>("NomePagador")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_pagador");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("tb_boleto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
